language: android

android:
  components:
    - tools
    - build-tools-23.0.3
    - platform-tools

#install:
#  # Build debug and release(run proguard)
#  - ./gradlew clean assemble assembleDebugAndroidTest -Pci --stacktrace --scan